//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from AQL.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IAQLListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class AQLBaseListener : IAQLListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="AQLParser.prog"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProg([NotNull] AQLParser.ProgContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AQLParser.prog"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProg([NotNull] AQLParser.ProgContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AQLParser.importList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImportList([NotNull] AQLParser.ImportListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AQLParser.importList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImportList([NotNull] AQLParser.ImportListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AQLParser.def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDef([NotNull] AQLParser.DefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AQLParser.def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDef([NotNull] AQLParser.DefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AQLParser.network"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNetwork([NotNull] AQLParser.NetworkContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AQLParser.network"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNetwork([NotNull] AQLParser.NetworkContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AQLParser.inputs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInputs([NotNull] AQLParser.InputsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AQLParser.inputs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInputs([NotNull] AQLParser.InputsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AQLParser.inputList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInputList([NotNull] AQLParser.InputListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AQLParser.inputList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInputList([NotNull] AQLParser.InputListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AQLParser.inputOption"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInputOption([NotNull] AQLParser.InputOptionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AQLParser.inputOption"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInputOption([NotNull] AQLParser.InputOptionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AQLParser.outputs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOutputs([NotNull] AQLParser.OutputsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AQLParser.outputs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOutputs([NotNull] AQLParser.OutputsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AQLParser.outputContB"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOutputContB([NotNull] AQLParser.OutputContBContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AQLParser.outputContB"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOutputContB([NotNull] AQLParser.OutputContBContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AQLParser.routes"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRoutes([NotNull] AQLParser.RoutesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AQLParser.routes"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRoutes([NotNull] AQLParser.RoutesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AQLParser.routesB"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRoutesB([NotNull] AQLParser.RoutesBContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AQLParser.routesB"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRoutesB([NotNull] AQLParser.RoutesBContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AQLParser.routeIDList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRouteIDList([NotNull] AQLParser.RouteIDListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AQLParser.routeIDList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRouteIDList([NotNull] AQLParser.RouteIDListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AQLParser.routeIDListB"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRouteIDListB([NotNull] AQLParser.RouteIDListBContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AQLParser.routeIDListB"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRouteIDListB([NotNull] AQLParser.RouteIDListBContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AQLParser.metrics"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMetrics([NotNull] AQLParser.MetricsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AQLParser.metrics"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMetrics([NotNull] AQLParser.MetricsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AQLParser.metricList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMetricList([NotNull] AQLParser.MetricListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AQLParser.metricList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMetricList([NotNull] AQLParser.MetricListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AQLParser.metricListA"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMetricListA([NotNull] AQLParser.MetricListAContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AQLParser.metricListA"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMetricListA([NotNull] AQLParser.MetricListAContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AQLParser.metric"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMetric([NotNull] AQLParser.MetricContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AQLParser.metric"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMetric([NotNull] AQLParser.MetricContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AQLParser.serviceCount"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterServiceCount([NotNull] AQLParser.ServiceCountContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AQLParser.serviceCount"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitServiceCount([NotNull] AQLParser.ServiceCountContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AQLParser.paramList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParamList([NotNull] AQLParser.ParamListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AQLParser.paramList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParamList([NotNull] AQLParser.ParamListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AQLParser.paramListA"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParamListA([NotNull] AQLParser.ParamListAContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AQLParser.paramListA"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParamListA([NotNull] AQLParser.ParamListAContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AQLParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStmt([NotNull] AQLParser.StmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AQLParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStmt([NotNull] AQLParser.StmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AQLParser.stmtA"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStmtA([NotNull] AQLParser.StmtAContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AQLParser.stmtA"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStmtA([NotNull] AQLParser.StmtAContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AQLParser.else1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElse1([NotNull] AQLParser.Else1Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AQLParser.else1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElse1([NotNull] AQLParser.Else1Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AQLParser.else2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElse2([NotNull] AQLParser.Else2Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AQLParser.else2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElse2([NotNull] AQLParser.Else2Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AQLParser.elseIf"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElseIf([NotNull] AQLParser.ElseIfContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AQLParser.elseIf"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElseIf([NotNull] AQLParser.ElseIfContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AQLParser.branchBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBranchBody([NotNull] AQLParser.BranchBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AQLParser.branchBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBranchBody([NotNull] AQLParser.BranchBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AQLParser.funcBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncBody([NotNull] AQLParser.FuncBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AQLParser.funcBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncBody([NotNull] AQLParser.FuncBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AQLParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr([NotNull] AQLParser.ExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AQLParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr([NotNull] AQLParser.ExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AQLParser.actualParamList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterActualParamList([NotNull] AQLParser.ActualParamListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AQLParser.actualParamList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitActualParamList([NotNull] AQLParser.ActualParamListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AQLParser.actualParamListA"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterActualParamListA([NotNull] AQLParser.ActualParamListAContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AQLParser.actualParamListA"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitActualParamListA([NotNull] AQLParser.ActualParamListAContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AQLParser.funcCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncCall([NotNull] AQLParser.FuncCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AQLParser.funcCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncCall([NotNull] AQLParser.FuncCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AQLParser.aExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAExpr([NotNull] AQLParser.AExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AQLParser.aExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAExpr([NotNull] AQLParser.AExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AQLParser.aExpr2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAExpr2([NotNull] AQLParser.AExpr2Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AQLParser.aExpr2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAExpr2([NotNull] AQLParser.AExpr2Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AQLParser.aTerm"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterATerm([NotNull] AQLParser.ATermContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AQLParser.aTerm"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitATerm([NotNull] AQLParser.ATermContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AQLParser.aTerm2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterATerm2([NotNull] AQLParser.ATerm2Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AQLParser.aTerm2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitATerm2([NotNull] AQLParser.ATerm2Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AQLParser.aFactor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAFactor([NotNull] AQLParser.AFactorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AQLParser.aFactor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAFactor([NotNull] AQLParser.AFactorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AQLParser.intOrDouble"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIntOrDouble([NotNull] AQLParser.IntOrDoubleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AQLParser.intOrDouble"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIntOrDouble([NotNull] AQLParser.IntOrDoubleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AQLParser.bExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBExpr([NotNull] AQLParser.BExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AQLParser.bExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBExpr([NotNull] AQLParser.BExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AQLParser.b1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterB1([NotNull] AQLParser.B1Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AQLParser.b1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitB1([NotNull] AQLParser.B1Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AQLParser.b2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterB2([NotNull] AQLParser.B2Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AQLParser.b2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitB2([NotNull] AQLParser.B2Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AQLParser.b3"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterB3([NotNull] AQLParser.B3Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AQLParser.b3"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitB3([NotNull] AQLParser.B3Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AQLParser.aToBExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAToBExpr([NotNull] AQLParser.AToBExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AQLParser.aToBExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAToBExpr([NotNull] AQLParser.AToBExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AQLParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType([NotNull] AQLParser.TypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AQLParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType([NotNull] AQLParser.TypeContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
