//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from AQL.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="AQLParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IAQLVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProg([NotNull] AQLParser.ProgContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.importList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImportList([NotNull] AQLParser.ImportListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDef([NotNull] AQLParser.DefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.network"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNetwork([NotNull] AQLParser.NetworkContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.inputs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInputs([NotNull] AQLParser.InputsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.inputList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInputList([NotNull] AQLParser.InputListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.inputOption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInputOption([NotNull] AQLParser.InputOptionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.outputs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOutputs([NotNull] AQLParser.OutputsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.outputContB"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOutputContB([NotNull] AQLParser.OutputContBContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.routes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRoutes([NotNull] AQLParser.RoutesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.routesB"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRoutesB([NotNull] AQLParser.RoutesBContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.routeIDList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRouteIDList([NotNull] AQLParser.RouteIDListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.routeIDListB"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRouteIDListB([NotNull] AQLParser.RouteIDListBContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.metrics"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMetrics([NotNull] AQLParser.MetricsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.metricList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMetricList([NotNull] AQLParser.MetricListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.metricListA"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMetricListA([NotNull] AQLParser.MetricListAContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.metric"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMetric([NotNull] AQLParser.MetricContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.serviceCount"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitServiceCount([NotNull] AQLParser.ServiceCountContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.paramList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParamList([NotNull] AQLParser.ParamListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.paramListA"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParamListA([NotNull] AQLParser.ParamListAContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStmt([NotNull] AQLParser.StmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.stmtA"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStmtA([NotNull] AQLParser.StmtAContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.else1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElse1([NotNull] AQLParser.Else1Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.else2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElse2([NotNull] AQLParser.Else2Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.elseIf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElseIf([NotNull] AQLParser.ElseIfContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.branchBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBranchBody([NotNull] AQLParser.BranchBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.funcBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncBody([NotNull] AQLParser.FuncBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr([NotNull] AQLParser.ExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.actualParamList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitActualParamList([NotNull] AQLParser.ActualParamListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.actualParamListA"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitActualParamListA([NotNull] AQLParser.ActualParamListAContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.funcCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncCall([NotNull] AQLParser.FuncCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.aExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAExpr([NotNull] AQLParser.AExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.aExpr2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAExpr2([NotNull] AQLParser.AExpr2Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.aTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitATerm([NotNull] AQLParser.ATermContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.aTerm2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitATerm2([NotNull] AQLParser.ATerm2Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.aFactor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAFactor([NotNull] AQLParser.AFactorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.intOrDouble"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntOrDouble([NotNull] AQLParser.IntOrDoubleContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.bExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBExpr([NotNull] AQLParser.BExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.b1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitB1([NotNull] AQLParser.B1Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.b2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitB2([NotNull] AQLParser.B2Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.b3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitB3([NotNull] AQLParser.B3Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.aToBExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAToBExpr([NotNull] AQLParser.AToBExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType([NotNull] AQLParser.TypeContext context);
}
