//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:/Users/thoma/Documents/GitHub/AQL/Interpreter/AQL.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="AQLParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IAQLVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.programEOF"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgramEOF([NotNull] AQLParser.ProgramEOFContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] AQLParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.importStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImportStatement([NotNull] AQLParser.ImportStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDefinition([NotNull] AQLParser.DefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.functionDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionDefinition([NotNull] AQLParser.FunctionDefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.constDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstDefinition([NotNull] AQLParser.ConstDefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.formalParameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFormalParameterList([NotNull] AQLParser.FormalParameterListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.networks"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNetworks([NotNull] AQLParser.NetworksContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.queueDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQueueDefinition([NotNull] AQLParser.QueueDefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.networkDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNetworkDefinition([NotNull] AQLParser.NetworkDefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.networkExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNetworkExpression([NotNull] AQLParser.NetworkExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.inputOutputNetworkExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInputOutputNetworkExpression([NotNull] AQLParser.InputOutputNetworkExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.instanceNetworkExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstanceNetworkExpression([NotNull] AQLParser.InstanceNetworkExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.routesList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRoutesList([NotNull] AQLParser.RoutesListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.routes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRoutes([NotNull] AQLParser.RoutesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.routesId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRoutesId([NotNull] AQLParser.RoutesIdContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.routesValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRoutesValue([NotNull] AQLParser.RoutesValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.probabilityIdList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProbabilityIdList([NotNull] AQLParser.ProbabilityIdListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.metrics"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMetrics([NotNull] AQLParser.MetricsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.metric"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMetric([NotNull] AQLParser.MetricContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.namedMetric"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamedMetric([NotNull] AQLParser.NamedMetricContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.simulateDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimulateDefinition([NotNull] AQLParser.SimulateDefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] AQLParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.whileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhileStatement([NotNull] AQLParser.WhileStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.variableDeclarationStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableDeclarationStatement([NotNull] AQLParser.VariableDeclarationStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.assignStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignStatement([NotNull] AQLParser.AssignStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfStatement([NotNull] AQLParser.IfStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.elseIfStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElseIfStatement([NotNull] AQLParser.ElseIfStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.elseStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElseStatement([NotNull] AQLParser.ElseStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] AQLParser.BlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnStatement([NotNull] AQLParser.ReturnStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.expressionList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionList([NotNull] AQLParser.ExpressionListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] AQLParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperator([NotNull] AQLParser.OperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.andOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAndOperator([NotNull] AQLParser.AndOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.orOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOrOperator([NotNull] AQLParser.OrOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.addOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAddOperator([NotNull] AQLParser.AddOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.subtractOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubtractOperator([NotNull] AQLParser.SubtractOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.divisionOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDivisionOperator([NotNull] AQLParser.DivisionOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.equalOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEqualOperator([NotNull] AQLParser.EqualOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.inEqualOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInEqualOperator([NotNull] AQLParser.InEqualOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.greaterThanOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGreaterThanOperator([NotNull] AQLParser.GreaterThanOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.greaterThanOrEqualOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGreaterThanOrEqualOperator([NotNull] AQLParser.GreaterThanOrEqualOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.lessThanOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLessThanOperator([NotNull] AQLParser.LessThanOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.lessThanOrEqualOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLessThanOrEqualOperator([NotNull] AQLParser.LessThanOrEqualOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryExpression([NotNull] AQLParser.UnaryExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.negationExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNegationExpression([NotNull] AQLParser.NegationExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.negativeExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNegativeExpression([NotNull] AQLParser.NegativeExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.parenthesesExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParenthesesExpression([NotNull] AQLParser.ParenthesesExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValue([NotNull] AQLParser.ValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionCall([NotNull] AQLParser.FunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.arrayInitialization"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayInitialization([NotNull] AQLParser.ArrayInitializationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.arrayIndexing"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayIndexing([NotNull] AQLParser.ArrayIndexingContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType([NotNull] AQLParser.TypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.typeKeyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeKeyword([NotNull] AQLParser.TypeKeywordContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.boolKeyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoolKeyword([NotNull] AQLParser.BoolKeywordContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.intKeyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntKeyword([NotNull] AQLParser.IntKeywordContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.doubleKeyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDoubleKeyword([NotNull] AQLParser.DoubleKeywordContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.stringKeyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStringKeyword([NotNull] AQLParser.StringKeywordContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.arrayType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayType([NotNull] AQLParser.ArrayTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.anyIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnyIdentifier([NotNull] AQLParser.AnyIdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.qualifiedIdList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQualifiedIdList([NotNull] AQLParser.QualifiedIdListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.qualifiedId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQualifiedId([NotNull] AQLParser.QualifiedIdContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.idList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdList([NotNull] AQLParser.IdListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifier([NotNull] AQLParser.IdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.bool"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBool([NotNull] AQLParser.BoolContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.int"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInt([NotNull] AQLParser.IntContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.double"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDouble([NotNull] AQLParser.DoubleContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AQLParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitString([NotNull] AQLParser.StringContext context);
}
