# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:


jobs:
  build:
    name: Build All Projects
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Restore dependencies
        run: dotnet restore AQL.sln

      - name: Build Engine/Library
        run: dotnet build Engine/Library/Engine.csproj --configuration Release

      - name: Build SimulationTest
        run: dotnet build Engine/SimulationTest/SimulationTest.csproj --configuration Release

      - name: Build Interpreter
        run: dotnet build Interpreter/Interpreter.csproj --configuration Release

      - name: Build SharedProject
        run: dotnet build SharedProject/SharedProject.csproj --configuration Release

      - name: Run SimulationTest
        run: dotnet test Engine/SimulationEngine.Tests/SimulationEngine.Tests.csproj --configuration Release
